apiVersion: v1
kind: Service
metadata:
  name: genre-detect-service
spec:
  type: LoadBalancer
  selector:
    app: genre-detect-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000 # Matches the containerPort in the Deployment